name: Generate pacman animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Customize SVG (black background + smaller size)
        run: |
          mkdir -p dist
          cp pacman-contribution-graph.svg dist/
          # Adiciona fundo preto
          sed -i '/<svg / s|>| style="background-color:black;">|' dist/pacman-contribution-graph.svg
          # Reduz tamanho (ex: 600x120)
          sed -i 's/viewBox="0 0 [0-9]* [0-9]*"/viewBox="0 0 600 120"/' dist/pacman-contribution-graph.svg

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
